---
title: "Análise - Modelos de Predição"
author: "Grupo"
date: "15 de dezembro de 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(caret)
library(here)
```

### Lendo os dados
```{r, warning=FALSE, message=FALSE}
treino <- read.csv(here("dataframes/true_car_listings_data_training.csv"), encoding = "latin1")
teste <- read.csv(here("dataframes/true_car_listings_data_test.csv"), encoding = "latin1")
```

### trainControl e preProcess
```{r}
fitControl <- trainControl(method = "repeatedcv",
                   number = 5,
                   repeats = 10,
                   verboseIter = TRUE)

preProcValues <- c("scale", "center", "nzv")
```

### Modelo Lasso
```{r}
model.lasso <- train(Price ~ .,
                    data = treino,
                    trControl = fitControl,
                    method = "lasso",
                    preProcess = preProcValues,
                    tuneLength = 15)
```

#### Variáveis Importantes e Predição
```{r}
model.lasso
ggplot(varImp(model.lasso))

pred.lasso <- predict(model.lasso, teste)

df.pred.lasso <- data.frame(predicao = pred.lasso, observado = teste$Price)

df.pred.lasso %>%
  ggplot(aes(x = predicao,
             y = observado - predicao,
             colour = observado - predicao)) +
  geom_jitter()

model.lasso$results %>%
  filter(RMSE == min(RMSE)) %>%
  select(RMSE, Rsquared)
```

### Modelo K-NN
```{r}
model.knn <- train(Price ~.,
           data = treino,
           trControl = controle,
           preProcess = preProcValues,
           method = "knn",
           tuneLength = 15)
```

#### Predição
```{r}
model.knn

pred.knn <- predict(model.knn, teste)

df.pred.knn <- data.frame(predicao = pred.knn, observado = teste$Price)

df.pred.knn %>%
  ggplot(aes(x = predicao,
             y = observado - predicao,
             colour = observado - predicao)) +
  geom_jitter()

model.knn$results %>%
  filter(RMSE == min(RMSE)) %>%
  select(RMSE, Rsquared)
```

### Rede Neural
```{r}
grid <- expand.grid(.decay = c(0.5, 0.1), .size = c(5, 6, 7))

numFolds <- trainControl(method = 'cv', number = 10, classProbs = TRUE, verboseIter = TRUE, summaryFunction = twoClassSummary, preProcOptions = list(thresh = 0.75, ICAcomp = 3, k = 5))

model.neuralNetwork <- train(Price ~., data = treino,
    method = "nnet", maxit = 1000, preProcess = preProcValues, trConrol = numFolds,tuneGrid = grid, trace = F, linout = 1)
```

#### Predição
```{r}
model.neuralNetwork

pred.neuralNetwork <- predict(model.neuralNetwork, teste)

df.pred.neuralNetwork <- data.frame(predicao = pred.neuralNetwork, observado = teste$Price)

df.pred.neuralNetwork %>%
  ggplot(aes(x = predicao,
             y = observado - predicao,
             colour = observado - predicao)) +
  geom_jitter()



model.neuralNetwork$results %>%
  filter(RMSE == min(RMSE)) %>%
  select(RMSE, Rsquared)
```

```{r}
plot(varImp(model.knn))
```

```{r}
plot(varImp(model.lasso))
```

```{r}
plot(varImp(model.neuralNetwork))
```

```{r}
summary(resamples(list(LM = model.lasso, NEURAL = model.neuralNetwork, KNN = model.knn)))
```

```{r}
plot(model.lasso)
```

```{r}
plot(model.knn)
```

```{r}
plot(model.neuralNetwork)
```

```{r}
model.neuralNetworkResults <- data.frame(teste$Price, pred.neuralNetwork, (pred.neuralNetwork - teste$price)^2)



rmse.knn <- sqrt(mean((pred.knn - teste$Price)^2))
rmse.knn
```


### Modelo K-NN
```{r}

treinoAjustado <- treino %>% select(Price, Mileage, Year)
testeAjustado <- teste %>% select(Price, Mileage, Year)


model.knnAdjusted <- train(Price ~ Mileage + Year,
           data = treinoAjustado,
           trControl = controle,
           preProcess = preProcValues,
           method = "knn",
           tuneLength = 15)
```


#### Predição KNN Melhorado
```{r}
model.knnAdjusted

pred.knnAdjusted <- predict(model.knnAdjusted, testeAjustado)

df.pred.knnAdjusted <- data.frame(predicao = pred.knnAdjusted, observado = testeAjustado$Price)

df.pred.knnAdjusted %>%
  ggplot(aes(x = predicao,
             y = observado - predicao,
             colour = observado - predicao)) +
  geom_jitter()

model.knnAdjusted$results %>%
  filter(RMSE == min(RMSE)) %>%
  select(RMSE, Rsquared)
```
